config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  # Static Pages
  get 'about' => 'static_pages#about'
  get 'pressroom' => 'static_pages#pressroom'
  get 'contact' => 'static_pages#contact'
  get 'Depression Stats' => 'static_pages#depression_stats'
  get 'faq' => 'static_pages#faq'
  get 'features' => 'static_pages#features'
  get 'home' => 'static_pages#home'
  get 'privacy' => 'static_pages#privacy_policy'
  get 'providers' => 'static_pages#providers'
  get 'resources' => 'static_pages#resources'
  get 'schools' => 'static_pages#schools'
  get 'sponsors' => 'static_pages#sponsors'
  get 'videos' => 'static_pages#videos'
  get 'solutions' => 'static_pages#solutions'
  get 'guardians' => 'static_pages#guardians'
  get 'substance_abuse' => 'static_pages#segmentation_substance'
  get 'employee_assistance' => 'static_pages#eap'
  get 'college_counseling' => 'static_pages#college_counseling'
  get 'integrative_care' => 'static_pages#integrative_care'
  # get 'managed_care' => 'static_pages#mcn'
  # get 'partners' => 'static_pages#partners'
  # get 'research' => 'static_pages#research'
  get 'telapeer' => 'static_pages#telapeer'
  get 'benefits' => 'static_pages#benefits'

  get :tips, to: 'users#tips'



  # App
  resources :alerts
  resources :appointments, only: [:show, :new, :create, :destroy]
  resources :assigned_exercises, only: [:index, :show, :create], controller: 'users/exercises_memberships' do
    resources :answers, only: [:create]
  end
  resource :charts
  devise_for :clinicians, skip: [:sessions, :passwords], controllers: {
    confirmations: 'users/confirmations',
    registrations: 'clinicians/registrations',
  }
  resources :clinician_entries, only: [:create]
  resources :clinicians do
    get :clinic_dashboard
    get :home, on: :collection
    get :search, on: :collection
  end


  resources :channels do
    post :follow, to: 'channels#follow', on: :member
    post :unfollow, to: 'channels#unfollow', on: :member
    resources :channel_assets
    get :channel_assets
  end

  get :my_activities, to: 'channels#my_activities'
  get :categories, to: 'meetings#categories'
  get :vet_meetings, to: 'meetings#vet_meetings'
  get :substance_meetings, to: 'meetings#substance_meetings'
  get :caregiver, to: 'meetings#caregiver'
  get :eating, to: 'meetings#eating'
  get :suicide_loss, to: 'meetings#suicide_loss'
  get :depression, to: 'meetings#depression'
  get :pregnancy_loss, to: 'meetings#pregnancy_loss'

  # resources :channel_assets

  namespace :clinicians do
    resources :members, only: [ :create, :destroy] do
      put 'approve' => 'members#approve', on: :member
    end
  end
  resources :consents, only: [:show]
  resources :contact_messages, only: [:create]
  resource :dashboard
  resources :diagnoses
  resources :entries do
    get :analysis, on: :collection
  end
  resources :exercises, only: [:show] do
    member do
      get :pdf, format: 'pdf'
    end
  end
  resources :facebook, only: [:new, :index]
  get 'auth/:provider/callback', to: 'facebook#create'
  get 'connect_to_facebook', to: 'facebook#new'
  resources :groups do
    member do
      get :add_clinician
    end
  end
  resources :facebook_posts, only: :index, defaults: { format: :json }
  resources :medical_conditions, only: [:show, :index]

  resources :meetings do
    post :join, to: 'meetings#join', on: :member
    get :invite, on: :member
    get :verify_password, on: :member
    post :verify_password_valid, on: :member

    resources :meeting_messages
  end

  get :my_meetings, to: 'meetings#my_meetings'


  resources :meeting_messages


  get 'meet_now', to: 'meetings#meet_now'
  get 'patient_meetings', to: 'patients#patient_meetings'


  devise_for :members, skip: [:sessions, :passwords], controllers: {
    registrations: 'members/registrations',
    confirmations: 'users/confirmations'
  }
  resources :members do
    get :home, on: :collection
    # post :add_journal_visible, :remove_journal_visible, on: :member
  end
  namespace :members do
    resources :observers, only: [:new, :create, :destroy, :edit, :update]
    resources :assigned_exercises, only: [:index, :show, :create, :destroy], controller: 'users/exercises_memberships'
  end
  resources :memberships, only: [:create, :update]
  resources :messages, only: [:create, :destroy] do
    post :mark_as_read, :mark_as_unread, on: :member
  end

  get 'My Dashboard' => 'dashboards#show'
  get 'My Team' => 'users#team'
  resources :observer_entries
  resources :observers do
    post :add_meds_visibility, :remove_meds_visibility, on: :member
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "/search-dsm5", to: "patients#search_dsm5", defaults: { format: :json }
  get "/search-icd10", to: "patients#search_icd10", defaults: { format: :json }
  resources :patients do
    resources :assigned_exercises, only: [:index, :show, :create, :destroy], controller: 'patients/exercises_memberships' do
      member do
        get :pdf, format: 'pdf'
      end
    end
    resource :scorecard, only: [:show]
    member do
      post :add_journal_visible, :remove_journal_visible
      get "collaboration"
      get "liability"
      get "medical_necessity"
      get "patient_summary"
    end
  end
  resources :pdf_emails, only: [:create]
  resources :prescriptions
  resources :pricing_plans, path: :plans, only: [:index]
  get 'Register Clinician' => 'clinicians#new'
  resources :schedules, only: [:show, :index], param: :member_id
  get 'signup' => 'members#new'
  get 'socials' => 'socials#index'

  get 'rmeetings' => 'rmeetings#index'
  get '/rmeetings/:id', to: 'rmeetings#index', as: 'id'

  resources :subscriptions, only: [:index, :create, :update]
  get 'summary' => 'dashboards#summary'
  resources :symptoms do
    post :add_tracked, on: :member
    put :remove_tracked, on: :member
    post :tracked, on: :collection
  end
  devise_for :users, skip: [:registrations], controllers: {
    confirmations: 'users/confirmations',
    invitations: 'users/invitations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get "users/password_expired", to: "users/password_expired#show", as: "user_password_expired"
    put "users/password_expired", to: "users/password_expired#update", as: ""
  end

  resources :users do
    collection do
      get 'invite_clinician'
      get 'invite_member'
      get 'invite_observer'
      get 'observations'
      get 'prescription_review'
      get 'make_observation'
      get 'observee_consistency_data'
      get 'team'
    end
  end

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API
  namespace :api, defaults:{format: :json} do
    scope module: :v1 do
      resource :aggregate, only: [:show]
      resources :alerts, only: [:create, :index]
      scope module: :clinicians do
        resources :members, only: [:destroy]
        put 'members/:clinician_id/approve' => 'members#approve'
      end
      resource :dashboard, only: [:show]
      resources :drugs, only: [:index]
      resources :entries, only: [:create, :index]
      resources :entries_prescriptions, only: [:create, :index, :show]
      resource  :goal_center, only: [:show]
      resources :journals, only: [:index, :show]

      resources :meetings, only: [:index, :create, :update] do
        member do
          post :invite_users # /api/meetings/:id/invite_users
        end
        post :join, to: 'meetings#join', on: :member
        get :verify_password, on: :member
        post :verify_password_valid, on: :member
        get :meeting_users, to: 'meetings#meeting_user'
        get :meeting_user, to: 'meetings#get_a_meeting_user', on: :member
        resources :meeting_users do
          member do
            post :remove
          end
        end
        resources :meeting_messages, only: [:index, :create]

      end
      resources :members, only: [] do
        resources :clinicians, only: [:index], to: "members/clinicians#index"
      end
      resources :memberships, only: [:index, :update]
      resources :messages, only: [:index, :create, :destroy] do
        patch :mark_as_read, :mark_as_unread, on: :member
      end
      scope module: :members do
        resources :observers, only: [:create, :destroy, :update]
      end
      resources :observations_on_me, only: [:index, :create, :update]
      resources :observations_of_others, only: [:index]
      namespace :observations_of_others do
        resources :prescriptions, only: [:index]
        resources :entries, only: [:index]
        resources :people, only: [:index]
        resource :consistency_chart, only: [:show]
      end
      resources :observer_entries, only: [:create]
      resources :passwords, only: [:create]
      resources :prescriptions, only: [:index, :create, :update]
      resource :session, only: [:create, :destroy]
      resources :symptoms, only: [:create, :index]
      resource :tracked_symptoms, only: [:update] do
        get :index, path: ''
      end
      resource :user, only: [:show, :update]
      resources :users, only: [:create] do
        get 'time_zones', on: :collection
        get 'twilio_token'
      end
    end
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :meeting_messages
  has_many :meeting_users
  # has_many :messages, through: :meeting_messages
  has_many :users, through: :meeting_users
  has_one :channel

  validates :password, presence: true, if: :private?
  before_save :set_end_time

  scope :inprogress, -> { where("end_time > ?", Time.current).where("start_time < ?", 15.minutes.from_now).where("status != ?", "complete") }
  scope :complete, -> { where("end_time < ?", Time.current) }
  # TODO maybe we want to share with other that there are people "Wating" in the meeting
  # for the meeting to start
  scope :waiting, -> { where(status: 'waiting') }
  scope :scheduled, -> { where("start_time > ?", Time.current).where("status != ?", "complete") }


  attr_accessor :date, :time

  def private?
    privacy == true
  end

  def complete?
    status == 'complete'
  end

  def complete!
    update(status: 'complete', completed: Date.today)
  end

  def inprogress?
    status == 'in-progress'
  end

  def waiting?
    status == 'waiting'
  end

  def scheduled?
    status == 'scheduled'
  end

  def room_name
    super || "no room name"
  end

  def retrieve_twilio_participants
    api_key_sid = ENV.fetch("TWILIO_ACCOUNT_SID")
    api_key_secret = ENV.fetch("TWILIO_AUTH_TOKEN")
  
    client = Twilio::REST::Client.new api_key_sid, api_key_secret
  
    participants = client.video.rooms(room_name)
                        .participants.list(status: 'connected').each do |participant|
      puts participant.sid
    end
  end

  private

  def set_end_time
    self.end_time = start_time + duration_in_minutes
  end

  def duration_in_minutes
    duration ? duration.minutes : 0
  end

end

app/controllers/api/v1/meetings_controller.rb
class Api::V1::MeetingsController < Api::Controller
  before_action :set_meeting, only: [:join]

  def index
    @meetings = Meeting.all
    render :json => @meetings
  end


  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      (params[:user_invitations] || []).each do |user_id|
        MeetingInvitation.create(invited: User.find(user_id), meeting: @meeting, creator: current_user)
      end
      render json: @meeting, status: :created
    else
      render json: @meeting.errors, status: :unprocessable_entity
    end
  end


  def invite_users
    # TODO: take care of the scenario where an id in the "user_invitations" array is not a valid user
    # User.find(params[:user_invitations]).each do |user|
    # ... (create the invitation)
    # end
    @meeting = Meeting.find(params[:id])

    (params[:user_invitations]).each do |user_id|
      invite = MeetingInvitation.find_or_initialize_by(invited: User.find(user_id), meeting: @meeting, creator: current_user)
      if invite.persisted?
        invite.send_invitation
      else
        invite.save!
      end
    end
    render json: {}, status: :created
  end

  def join
    @mu = MeetingUser.new(meeting: @meeting, user: current_user, display_name: current_user.user_id, email: current_user.email)

    if @mu.save
      render json: @meeting, status: :joined
    else
      render json: @meeting, status: :failed_to_join
    end
  end

  def remove_participant
    @attendees = MeetingUser.where("meeting_id = ?", params[:meeting_id])
    @attendee = @attendees.find_by(user: params[:id])

  end

  def verify_password
    @meeting = Meeting.find(params[:id])
  end

  def verify_password_valid
    @meeting = Meeting.find(params[:id])

    puts params[:meeting][:password]
    puts params
    
    if params[:meeting][:password] != @meeting.password
      render json: { "is_valid" => false }
    else
      render json: { "is_valid" => true }
    end
  end

  def meeting_user
    @attendees = MeetingUser.where("meeting_id = ?", params[:meeting_id])

    render json: @attendees
  end


  def update
    @meeting = Meeting.find(params[:id])
    authorize! :update, @meeting
    if @meeting.update_attributes(meeting_params)
      respond_with @meeting, serializer: MeetingSerializer
    else
      render json: {success: false, errors: @meeting.errors}
    end
  end


  private
    def meeting_params
      params.require(:meeting).permit(:id, :name, :meeting_type, :start_time, :end_time, :duration, :status, :room_name,
                                      :privacy, :topic, :special_focus, :host, :user_id, :display_name, :password )
    end

    def set_meeting
      @meeting = Meeting.find(params[:id])
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_end_live_channel_meeting.html.erb
<%= form_for(@meeting) do |f| %>
    <% if @meeting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
          <ul>
            <% @meeting.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="hidden">
      <%= f.text_field :status, value: 'complete' %>
    </div>

    <br>
    <hr>
    <div class="row">
      <div class="col-md-12">
        <div class="actions" style="float: right">
          <%= f.submit 'End Meeting', class:"btn btn-primary", style: "border-radius: 0; border-color: #F19A20; background-color: #F19A20; color: white  " %>
        </div>
<% end %>
</div>
</div>

app/views/meetings/_inprogress_meetings.html.erb
<table id= "meetingsInprogressTable" cellpadding="0" cellspacing="0" border="0" class="dataTable table-responsive table-striped table-hover table-highlight table-bordered"  >
  <thead>
  <tr id="">
    <th style="border-bottom-color: transparent; border: none; width: 10% "></th>
    <th style="border-bottom-color: transparent; border: none; width: 20% ">
      Your Current Timezone is:
    </th>
    <th class="hidden-xs" style="border-bottom-color: transparent; border: none; width: 60% ">
      <%= form_for(@user) do |tz| %>
        <%= tz.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {}, { class: 'form-control'} %>
        <%= tz.submit "Save changes", class: "btn btn-primary", style: "border-radius: 0; background-color: #F19A20; border-color:  #F19A20" %>
      <% end %>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @meetings.inprogress.order("start_time desc").each do |meeting| %>
      <tr>
        <td style="font-size: large"><%= link_to 'Join', meeting %></td>
        <td>
          <i>
            <%= meeting.meeting_users.in_meeting.count  %> attendees
          </i><br>
          hosted by: <%= meeting.host %><br>
          <%=  meeting.privacy.present?  ? "Private" : "" %>
        </td>
        <td><%= meeting.meeting_type %><br>
          <span style="font-size: large"><b><%= meeting.name %></b></span> <br>
          <%= meeting.topic %>
          <span style="font-size: small"> <%= meeting.special_focus %></span>
          <% if meeting.user_id == current_user.id %>
              <span style="float: right">
                <%= link_to 'Edit', edit_meeting_path(meeting) %><br>
              </span><br>
              <span style="float: right">
                <button type="button"
                        class="btn btn-primary"
                        style="vertical-align: bottom; margin-left: 2%; padding: 4px; background-color: #F19A20; font-size: x-small; border-color: orange; border-radius: 0;"
                        data-toggle="modal"
                        data-target="#meetingInprogressDetails2Modal<%=meeting.id %>">
                  <b>Details</b>
                </button>
              </span>
          <% else %>
            <span style="float: right">
              <button type="button"
                      class="btn btn-primary"
                      style="vertical-align: bottom; margin-left: 2%; padding: 4px; background-color: #F19A20; font-size: x-small; border-color: orange; border-radius: 0;"
                      data-toggle="modal"
                      data-target="#meetingInprogressDetails1Modal<%=meeting.id %>">
                <b>Details</b>
              </button>
             </span>
              <div class="modal fade" id="meetingInprogressDetails1Modal<%=meeting.id %>" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document">
                  <div class="modal-content" style="border-radius: 0">
                    <div class="modal-body">
                      <div class="row" style="margin-left: -20px">
                        <div class="col-md-12">
                          <div class="panel" style="border: 1px solid; border-radius: 0; border-color: lightgrey; background-color: #326867 ">
                            <div class="panel-body text-center">
                              <h1 style="margin: 4px; margin-bottom: 10px; margin-top: 10px; color: white ">
                                Meeting Details
                              </h1>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <%= render partial: "meeting_details", locals: {meeting: meeting} %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
          <div class="modal fade" id="meetingInprogressDetails2Modal<%=meeting.id %>" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content" style="border-radius: 0">
                <div class="modal-body">
                  <div class="row" style="margin-left: -20px">
                    <div class="col-md-12">
                      <div class="panel" style="border: 1px solid; border-radius: 0; border-color: lightgrey; background-color: #326867 ">
                        <div class="panel-body text-center">
                          <h1 style="margin: 4px; margin-bottom: 10px; margin-top: 10px; color: white ">
                            Meeting Details
                          </h1>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <%= render partial: "meeting_details", locals: {meeting: meeting} %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/_my_completed_meetings.html.erb
<table id= "meetingsCompletedTable" cellpadding="0" cellspacing="0" border="0" class="dataTable table-responsive table-striped table-hover table-highlight table-bordered"  >
  <thead>
  <tr>
    <th class="hidden"></th>
    <th class="hidden"></th>
    <th class="hidden"></th>
    <th class="hidden"></th>

  </tr>
  </thead>
  <tbody>
  <% @meetings.complete.order("start_time DESC").each do |meeting| %>
    <tr>
      <td><span style="font-size: large"> <%= meeting.start_time.strftime("%A, %B %d") %></span><br>
        <%= meeting.start_time.strftime("%I:%M %p") %></td>
      <td>
        <%= meeting.host %>

      </td>
      <td><%= meeting.meeting_type %><br>
        <span style="font-size: large"><b><%= meeting.name %></b></span> <br>
        <%= meeting.topic %>
        <span style="font-size: small"> <%= meeting.special_focus %></span>
        <span style="float: right">
          <button type="button"
                  class="btn btn-primary"
                  style="vertical-align: bottom; margin-left: 2%; padding: 4px; background-color: #F19A20; font-size: x-small; border-color: orange; border-radius: 0;"
                  data-toggle="modal"
                  data-target="#meetingCompletedDetails1Modal<%=meeting.id %>">
            <b>Details</b>
          </button>
        </span>

        <div class="modal fade" id="meetingCompletedDetails1Modal<%= meeting.id %>" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content" style="border-radius: 0">
              <div class="modal-body">
                <div class="row" style="margin-left: -20px">
                  <div class="col-md-12">
                    <div class="panel" style="border: 1px solid; border-radius: 0; border-color: lightgrey; background-color: #326867 ">
                      <div class="panel-body text-center">
                        <h1 style="margin: 4px; margin-bottom: 10px; margin-top: 10px; color: white ">
                          Meeting Details
                        </h1>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <div class="row">
                      <div class="col-md-12">
                        <b  style="font-size: large"><%= meeting.meeting_type %></b><br>
                        <%= time_zone_offset(meeting.start_time, current_user.time_zone,  "%A, %B %d, %I:%M %p") %><br><br>
                        <p><b>Host:</b><br>
                          <%= meeting.host %>
                        </p>
                        <p><b>Conversation Name: </b><br>
                          <%= meeting.name %>
                        </p>
                        <p><b>Topic:</b> <br>
                          <%= meeting.topic %>
                        </p>
                        <p ><b>Focus:</b><br>
                          <%= meeting.special_focus %>
                        </p>
                      </div>
                      <div class="col-md-12">
                        <% if current_user.id == 1 %>
                          <p><b>Meeting Users:</b></p>
                          <table id="mu_details">
                            <thead>
                            <tr id="">
                              <th>User ID</th>
                              <th>Display Name</th>
                              <th>Joined At</th>
                              <th>Left At</th>
                              <th>User Left?</th>
                            </tr>
                            </thead>
                            <tbody>
                            <% meeting.meeting_users.each do |mu| %>
                              <td><%= mu.user_id  %></td>
                              <td><%= mu.display_name  %></td>
                              <td><%= mu.created_at.strftime(" %B %d, %I:%M %p")   %></td>
                              <td><%= mu.updated_at.strftime(" %B %d, %I:%M %p")   %></td>
                              <td><%= mu.departed  %></td>
                              </tbody>
                            <% end %>
                            </table>
                        <% else %>
                        <% end %>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </td>
      <td>
        <%= link_to 'Edit', edit_meeting_path(meeting) %> |
        <%= link_to 'Cancel', meeting, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/_my_inprogress_meetings.html.erb
<table id= "meetingsInprogressTable" cellpadding="0" cellspacing="0" border="0" class="dataTable table-responsive table-striped table-hover table-highlight table-bordered"  >
  <thead>
  <tr id="">
    <th style="border-bottom-color: transparent; border: none; width: 15% ">

    </th>
    <th style="border-bottom-color: transparent; border: none; width: 20% "></th>
    <th class="hidden-xs" style="border-bottom-color: transparent; border: none; width: 60% ">
    </th>
    <th style="border-bottom-color: transparent; border: none; width: 5% ">
    </th>
  </tr>
  </thead>
  <tbody>
  <% @meetings.inprogress.order("start_time desc").each do |meeting| %>
      <tr>
        <td><%= link_to 'Join', meeting %></td>
        <td> In-Progress  <br>
          <i><%= meeting.meeting_users.in_meeting.count %> attendees </i><br>
          <%=  meeting.privacy.present?  ? "Private" : "" %>

        </td>

        <td><%= meeting.meeting_type %><br>
          <span style="font-size: large"><b><%= meeting.name %></b></span> <br>
          <%= meeting.topic %>
          <span style="font-size: small"> <%= meeting.special_focus %></span></td>
        <!--<td><= meeting.status %></td>-->
        <!--<td><= meeting.privacy %></td>-->
        <td>
          <span style="float: right">
          <%= link_to 'Edit', edit_meeting_path(meeting) %>
            <!--<= link_to 'Cancel', meeting, method: :delete, data: { confirm: 'Are you sure?' } %>-->
          </span>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/_my_scheduled_meetings.html.erb
<table id= 'meetingsScheduledTable' cellpadding="0" cellspacing="0" border="0" class="dataTable table-responsive table-striped table-hover table-highlight table-bordered"  >
  <thead>
  <tr id="meetingsScheduledTable">
    <th style="border-bottom-color: transparent; border: none; width: 25%  "></th>
    <th class="hidden-xs" style="border-bottom-color: transparent; border: none; width: 75%  ">Start or Join a Peer Support Meeting Now!</th>
    <th style="border-bottom-color: transparent; border: none; width: 5%  ">
      <div class="col-md-12 hidden-xs" align="center" >
        <button type="button"
                class="btn btn-primary"
                style="vertical-align: bottom; margin: 2%; padding: 10px; background-color: #F19A20; border-color: orange; border-radius: 0; float: right "
                data-toggle="modal"
                data-target="#scheduleMeetingModal">
          <b>Schedule Meeting</b>
        </button>
      </div>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @meetings.scheduled.order("start_time desc").each do |meeting| %>
      <tr>
        <td style="width: 28%"><span style="font-size: large"> <%= time_zone_offset(meeting.start_time, current_user.time_zone,  "%A, %B %d") %></span><br>
          <%= time_zone_offset(meeting.start_time, current_user.time_zone,  "%I:%M %p") %><br>
          <%=  meeting.privacy.present?  ? "Private" : "" %>
        </td>
        <td style="width: 65%"><%= meeting.meeting_type %><br>
          <span style="font-size: large"><b><%= meeting.name %></b></span> <br>
          <%= meeting.topic %>
          <span style="font-size: small">   <%= meeting.special_focus %></span>
        </td>
        <td style="width: 7%">
          <span style="float: right">
          <%= link_to 'Edit', edit_meeting_path(meeting) %>
            <!--<= link_to 'Cancel', meeting, method: :delete, data: { confirm: 'Are you sure?' } %>-->
          </span>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/_waiting_meetings.html.erb
<table id= "meetingsWaitingTable" cellpadding="0" cellspacing="0" border="0" class="dataTable table-responsive table-striped table-hover table-highlight table-bordered" >
  <thead>
  <tr>
    <th colspan="4" style="border-bottom-color: transparent">Start or Join a Peer Support Meeting Now!</th>
    <!--<th>Status</th>-->
    <th  style="border-bottom-color: transparent"></th>
  </tr>
  </thead>
  <tbody>
  <% @meetings.waiting.each do |meeting| %>
      <tr>
        <td><%= link_to 'Join', meeting %></td>
        <td><span style="font-size: large"> <%= meeting.start_time.strftime("%A, %B %d") %></span><br>
          <%= meeting.start_time.strftime("%I:%M %p") %></td>

        <td><%= meeting.meeting_type %><br><br>
          <span style="font-size: large"><b><%= meeting.name %></b></span> <br>
          <%= meeting.topic %>
          <span style="font-size: small"> <%= meeting.special_focus %></span></td>
        <!--<td><= meeting.status %></td>-->
        <td><%= meeting.privacy %></td>
        <td>

          <%= link_to 'Edit', edit_meeting_path(meeting) %> |
          <%= link_to 'Cancel', meeting, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/meetings/meet_now.html.erb
<%= render 'meet_now'%>

app/views/meetings/new.html.erb
<h1>Schedule Meeting</h1>

<%= render 'form' %>